module.exports = {
  ABOUT_ACTIONS: {
    GET_DETAIL: 'ABOUT_ACTIONS:GET_DETAIL'
  },

  QUOTE_ACTIONS: {
    GET_DETAIL: 'QUOTE_ACTIONS:GET_DETAIL'
  },

  ROUTE_ACTIONS: {
    TRANSITION: 'ROUTE_ACTIONS.TRANSITION'
  }
};